name: my_nav_rail
description: A Navigation Rail for Flutter
maintainer: Erkinjon (@MrErkinjon)
version: 0.0.1
homepage: https://github.com/MrErkinjon/my_nav_rail

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: